### ISSUE TITLE
好多番外篇的链接都失效了，

### ISSUE THREAD

**Issue by cwhuasmile** [CodecWang/OpenCV-Python-Tutorial#14]
好多番外篇的链接都失效了，打开就是404

**Comment by CodecWang** [comment]
你好，因为之前的域名到期了， 现在是http://codec.wang/
刚刚已经修复完成🙂

**Comment by cwhuasmile** [comment]
> 你好，因为之前的域名到期了， 现在是http://codec.wang/
> 刚刚已经修复完成🙂

非常感谢你的回复，我又看了一下，问题依然存在。应该是我没有表达清楚，我列出来俩个地方你看一下：
1，OpenCV-Python教程10：平滑图像 ——>目录——>教程——>滤波与模糊——>【番外篇：卷积基础(图片边框)】点击跳转出来的是404页面。
2，OpenCV-Python教程07：图像几何变换 ——>目标——>教程——>【番外篇：仿射变换与透视变换】点击跳转出来的也是404页面。

**Comment by CodecWang** [comment]
噢噢，抱歉，这个忘记修正了。刚已修正完成。如还有其他问题，也请指正😀
