### ISSUE TITLE
什么时候出新章节啊？

### ISSUE THREAD

**Issue by x12901** [CodecWang/OpenCV-Python-Tutorial#15]
学完了，感觉还是有点吃力，大佬能到出点案例实践一下吗？

**Comment by CodecWang** [comment]
可以多找些实例practice下，我教程中的挑战篇也算。
然后最好可以自己梳理脑图或笔记之类的，总之关键在于练习后的复习梳理。
另外，现在工作一来很忙，二来不是从事图像处理相关的，所以原计划的后面三个篇章短期内很难更新，抱歉🤣
