### ISSUE TITLE
教程网站是挂了吗？打不开了

### ISSUE THREAD

**Issue by runningBolin** [CodecWang/OpenCV-Python-Tutorial#21]
教程网站是挂了吗？打不开了

**Comment by CodecWang** [comment]
你好，

刚打开看了下，没问题的：http://codec.wang/#/opencv/

________________________________
发件人: bolin <notifications@github.com>
发送时间: 2021年2月7日 9:17
收件人: CodecWang/OpenCV-Python-Tutorial <OpenCV-Python-Tutorial@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [CodecWang/OpenCV-Python-Tutorial] 教程网站是挂了吗？打不开了 (#21)


教程网站是挂了吗？打不开了

―

**Comment by dxalyjz** [comment]
我也打不开了,可能是在国外的问题?

**Comment by CodecWang** [comment]
@dxalyjz @runningBolin 
服务器问题，已修复，请重新尝试～http://codec.wang/#/opencv/
